// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProjectApprovalDbContext))]
    partial class ProjectApprovalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApprovalRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("Area");

                    b.HasIndex("Type");

                    b.ToTable("ApprovalRule", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApproverRoleId = 1,
                            MaxAmount = 100000m,
                            MinAmount = 0m,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            ApproverRoleId = 2,
                            MaxAmount = 20000m,
                            MinAmount = 5000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            ApproverRoleId = 2,
                            Area = 2,
                            MaxAmount = 20000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            ApproverRoleId = 3,
                            MaxAmount = 0m,
                            MinAmount = 20000m,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 5L,
                            ApproverRoleId = 2,
                            Area = 1,
                            MaxAmount = 0m,
                            MinAmount = 5000m,
                            StepOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6L,
                            ApproverRoleId = 1,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 7L,
                            ApproverRoleId = 4,
                            Area = 2,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 8L,
                            ApproverRoleId = 2,
                            Area = 2,
                            MaxAmount = 30000m,
                            MinAmount = 10000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 9L,
                            ApproverRoleId = 3,
                            Area = 3,
                            MaxAmount = 0m,
                            MinAmount = 30000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 10L,
                            ApproverRoleId = 4,
                            MaxAmount = 50000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApprovalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Observed"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApproverRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ApproverRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Líder de Área"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comité Técnico"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Operaciones"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observations")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("ProjectProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ProjectProposalId");

                    b.HasIndex("Status");

                    b.ToTable("ProjectApprovalStep", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("CreateBy");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("ProjectProposal", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ProjectType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mejora de Procesos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Innovación y Desarrollo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Infraestructura"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Capacitación Interna"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jferreyra@unaj.com",
                            Name = "José Ferreyra",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "alucero@unaj.com",
                            Name = "Ana Lucero",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "gmolinas@unaj.com",
                            Name = "Gonzalo Molinas",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "lolivera@unaj.com",
                            Name = "Lucas Olivera",
                            Role = 3
                        },
                        new
                        {
                            Id = 5,
                            Email = "dfagundez@unaj.com",
                            Name = "Danilo Fagundez",
                            Role = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "ggalli@unaj.com",
                            Name = "Gabriel Galli",
                            Role = 4
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApprovalRule", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.ApproverRole", "ApprovalRuleApproverRole")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.Area", "ApprovalRuleArea")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("Area")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Infrastructure.Persistence.Entities.ProjectType", "ApprovalRuleType")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovalRuleApproverRole");

                    b.Navigation("ApprovalRuleArea");

                    b.Navigation("ApprovalRuleType");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectApprovalStep", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.ApproverRole", "StepApproverRole")
                        .WithMany("ProjectApprovalSteps")
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.User", "StepUser")
                        .WithMany("ProjectApprovalSteps")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Infrastructure.Persistence.Entities.ProjectProposal", "StepProjectProposal")
                        .WithMany("ProjectApprovalSteps")
                        .HasForeignKey("ProjectProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.ApprovalStatus", "StepApprovalStatus")
                        .WithMany("ProjectApprovalSteps")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StepApprovalStatus");

                    b.Navigation("StepApproverRole");

                    b.Navigation("StepProjectProposal");

                    b.Navigation("StepUser");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectProposal", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Area", "ProjectProposalArea")
                        .WithMany("ProjectProposals")
                        .HasForeignKey("Area")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.User", "ProjectProposalUser")
                        .WithMany("ProjectProposals")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.ApprovalStatus", "ProjectProposalApprovalStatus")
                        .WithMany("ProjectProposals")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.ProjectType", "ProjectProposalType")
                        .WithMany("ProjectProposals")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectProposalApprovalStatus");

                    b.Navigation("ProjectProposalArea");

                    b.Navigation("ProjectProposalType");

                    b.Navigation("ProjectProposalUser");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.ApproverRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApprovalStatus", b =>
                {
                    b.Navigation("ProjectApprovalSteps");

                    b.Navigation("ProjectProposals");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ApproverRole", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("ProjectApprovalSteps");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Area", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("ProjectProposals");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectProposal", b =>
                {
                    b.Navigation("ProjectApprovalSteps");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProjectType", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("ProjectProposals");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("ProjectApprovalSteps");

                    b.Navigation("ProjectProposals");
                });
#pragma warning restore 612, 618
        }
    }
}
